// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	Signature   string             `json:"signature"`
	RequestData []byte             `json:"request_data"`
	RequestID   string             `json:"request_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuthorizeCode struct {
	Code        string             `json:"code"`
	Active      bool               `json:"active"`
	RequestData []byte             `json:"request_data"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BlacklistedJti struct {
	Jti       string             `json:"jti"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Client struct {
	ID            string             `json:"id"`
	Secret        []byte             `json:"secret"`
	RedirectUris  []byte             `json:"redirect_uris"`
	GrantTypes    []byte             `json:"grant_types"`
	ResponseTypes []byte             `json:"response_types"`
	Scopes        []byte             `json:"scopes"`
	Public        bool               `json:"public"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type IdpSession struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	UserAgent *string            `json:"user_agent"`
	IpAddress *string            `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type OidcSession struct {
	AuthorizeCode string             `json:"authorize_code"`
	RequestData   []byte             `json:"request_data"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ParSession struct {
	RequestUri  string             `json:"request_uri"`
	RequestData []byte             `json:"request_data"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PkceSession struct {
	Code        string             `json:"code"`
	RequestData []byte             `json:"request_data"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	Signature            string             `json:"signature"`
	Active               bool               `json:"active"`
	RequestData          []byte             `json:"request_data"`
	RequestID            string             `json:"request_id"`
	AccessTokenSignature *string            `json:"access_token_signature"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type SsfEvent struct {
	ID                pgtype.UUID        `json:"id"`
	EventType         string             `json:"event_type"`
	SubjectIdentifier *string            `json:"subject_identifier"`
	Payload           []byte             `json:"payload"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type SsfEventDelivery struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	StreamID    pgtype.UUID        `json:"stream_id"`
	Jti         string             `json:"jti"`
	SetToken    string             `json:"set_token"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	LastError   *string            `json:"last_error"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	SentAt      pgtype.Timestamptz `json:"sent_at"`
	AckedAt     pgtype.Timestamptz `json:"acked_at"`
}

type SsfStream struct {
	ID                  pgtype.UUID        `json:"id"`
	ClientID            *string            `json:"client_id"`
	Audience            []string           `json:"audience"`
	DeliveryMethod      string             `json:"delivery_method"`
	EndpointUrl         string             `json:"endpoint_url"`
	AuthorizationHeader *string            `json:"authorization_header"`
	EventsRequested     []string           `json:"events_requested"`
	EventsDelivered     []string           `json:"events_delivered"`
	Status              string             `json:"status"`
	StatusReason        *string            `json:"status_reason"`
	Description         *string            `json:"description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type SsfStreamSubject struct {
	ID                pgtype.UUID        `json:"id"`
	StreamID          pgtype.UUID        `json:"stream_id"`
	SubjectFormat     string             `json:"subject_format"`
	SubjectIdentifier string             `json:"subject_identifier"`
	Verified          bool               `json:"verified"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	PasswordHash  []byte             `json:"password_hash"`
	DisplayName   *string            `json:"display_name"`
	Role          string             `json:"role"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	AccountStatus string             `json:"account_status"`
}
