// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AckSSFDeliveries(ctx context.Context, arg AckSSFDeliveriesParams) error
	AckSSFDelivery(ctx context.Context, arg AckSSFDeliveryParams) error
	BlacklistJTI(ctx context.Context, arg BlacklistJTIParams) error
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CheckUsernameExists(ctx context.Context, username string) (bool, error)
	CleanupExpiredJTIs(ctx context.Context) error
	CleanupExpiredSessions(ctx context.Context) error
	CleanupOldSSFDeliveries(ctx context.Context) error
	CleanupOldSSFEvents(ctx context.Context) error
	CountClients(ctx context.Context) (int64, error)
	CountSSFEventDeliveries(ctx context.Context) (int64, error)
	CountSSFEventDeliveriesByStatus(ctx context.Context, status string) (int64, error)
	CountSSFEventDeliveriesByStream(ctx context.Context, streamID pgtype.UUID) (int64, error)
	CountSSFEventDeliveriesFiltered(ctx context.Context, arg CountSSFEventDeliveriesFilteredParams) (int64, error)
	CountSSFEvents(ctx context.Context) (int64, error)
	CountSSFStreams(ctx context.Context) (int64, error)
	CountSSFStreamsByStatus(ctx context.Context, status string) (int64, error)
	CountUserSessions(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// Access Tokens
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error
	// Authorization Codes
	CreateAuthorizeCode(ctx context.Context, arg CreateAuthorizeCodeParams) error
	CreateClient(ctx context.Context, arg CreateClientParams) error
	// ===================
	// IdP Sessions (for SLO)
	// ===================
	CreateIDPSession(ctx context.Context, arg CreateIDPSessionParams) (IdpSession, error)
	// OIDC Sessions
	CreateOIDCSession(ctx context.Context, arg CreateOIDCSessionParams) error
	CreateOwnerUser(ctx context.Context, arg CreateOwnerUserParams) (User, error)
	// PAR Sessions
	CreatePARSession(ctx context.Context, arg CreatePARSessionParams) error
	// PKCE Sessions
	CreatePKCESession(ctx context.Context, arg CreatePKCESessionParams) error
	// Refresh Tokens
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	// ===================
	// SSF: Events (normalized)
	// ===================
	CreateSSFEvent(ctx context.Context, arg CreateSSFEventParams) (SsfEvent, error)
	// ===================
	// SSF: Event Deliveries (normalized)
	// ===================
	CreateSSFEventDelivery(ctx context.Context, arg CreateSSFEventDeliveryParams) (SsfEventDelivery, error)
	// ===================
	// SSF: Streams
	// ===================
	CreateSSFStream(ctx context.Context, arg CreateSSFStreamParams) (SsfStream, error)
	// ===================
	// SSF: Stream Subjects
	// ===================
	CreateSSFStreamSubject(ctx context.Context, arg CreateSSFStreamSubjectParams) (SsfStreamSubject, error)
	// Users
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Admin creates a user with optional role
	CreateUserByAdmin(ctx context.Context, arg CreateUserByAdminParams) (User, error)
	DeleteAccessToken(ctx context.Context, signature string) error
	DeleteAccessTokenByRequestID(ctx context.Context, requestID string) error
	DeleteAllSSFStreamSubjects(ctx context.Context, streamID pgtype.UUID) error
	DeleteClient(ctx context.Context, id string) error
	DeleteExpiredAccessTokens(ctx context.Context) error
	DeleteExpiredAuthorizeCodes(ctx context.Context) error
	DeleteExpiredPARSessions(ctx context.Context) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteOIDCSession(ctx context.Context, authorizeCode string) error
	DeletePARSession(ctx context.Context, requestUri string) error
	DeletePKCESession(ctx context.Context, code string) error
	DeleteRefreshToken(ctx context.Context, signature string) error
	DeleteSSFStream(ctx context.Context, id pgtype.UUID) error
	DeleteSSFStreamSubject(ctx context.Context, arg DeleteSSFStreamSubjectParams) error
	GetAccessToken(ctx context.Context, signature string) (AccessToken, error)
	GetAccessTokenByRequestID(ctx context.Context, requestID string) (AccessToken, error)
	// ===================
	// Admin: Statistics
	// ===================
	GetActiveSessionCount(ctx context.Context) (int64, error)
	GetAdminUsers(ctx context.Context) ([]User, error)
	GetAuthorizeCode(ctx context.Context, code string) (AuthorizeCode, error)
	// OAuth Clients
	GetClient(ctx context.Context, id string) (Client, error)
	GetIDPSession(ctx context.Context, id pgtype.UUID) (IdpSession, error)
	GetOIDCSession(ctx context.Context, authorizeCode string) (OidcSession, error)
	GetOwnerUser(ctx context.Context) (User, error)
	GetPARSession(ctx context.Context, requestUri string) (ParSession, error)
	GetPKCESession(ctx context.Context, code string) (PkceSession, error)
	// Fetch deliveries ready for transmission (Push: queued/retry with next_retry_at <= now)
	// FOR UPDATE SKIP LOCKED ensures no duplicate processing in multi-instance environments
	GetPendingSSFDeliveries(ctx context.Context, limit int32) ([]GetPendingSSFDeliveriesRow, error)
	// Fetch deliveries for Poll (queued or sent but not acked)
	GetPollSSFDeliveries(ctx context.Context, arg GetPollSSFDeliveriesParams) ([]GetPollSSFDeliveriesRow, error)
	GetRecentLoginCount(ctx context.Context) (int64, error)
	GetRecentSSFDeliveryCount(ctx context.Context) (int64, error)
	GetRefreshToken(ctx context.Context, signature string) (RefreshToken, error)
	GetRefreshTokenByRequestID(ctx context.Context, requestID string) (RefreshToken, error)
	GetSSFDeliveryStats(ctx context.Context) (GetSSFDeliveryStatsRow, error)
	GetSSFEvent(ctx context.Context, id pgtype.UUID) (SsfEvent, error)
	GetSSFEventDelivery(ctx context.Context, id pgtype.UUID) (SsfEventDelivery, error)
	// Fetch a single delivery with all details needed for processing
	GetSSFEventDeliveryByIDWithDetails(ctx context.Context, id pgtype.UUID) (GetSSFEventDeliveryByIDWithDetailsRow, error)
	GetSSFEventDeliveryByJTI(ctx context.Context, jti string) (SsfEventDelivery, error)
	GetSSFStream(ctx context.Context, id pgtype.UUID) (SsfStream, error)
	GetSSFStreamByClientID(ctx context.Context, clientID *string) ([]SsfStream, error)
	GetSSFStreamSubject(ctx context.Context, arg GetSSFStreamSubjectParams) (SsfStreamSubject, error)
	// Subject が登録されているストリーム（enabled のみ）を取得
	GetStreamsBySubjectIdentifier(ctx context.Context, subjectIdentifier string) ([]SsfStream, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByIDIncludeInactive(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	HasOwner(ctx context.Context) (bool, error)
	InvalidateAuthorizeCode(ctx context.Context, code string) error
	InvalidateRefreshToken(ctx context.Context, signature string) error
	InvalidateRefreshTokenByRequestID(ctx context.Context, requestID string) error
	// Blacklisted JTIs
	IsJTIBlacklisted(ctx context.Context, jti string) (bool, error)
	// 特定の Subject がストリームに登録されているか確認
	IsSubjectInStream(ctx context.Context, arg IsSubjectInStreamParams) (bool, error)
	IsUserAdmin(ctx context.Context, id pgtype.UUID) (bool, error)
	IsUserAdminOrOwner(ctx context.Context, id pgtype.UUID) (bool, error)
	IsUserOwner(ctx context.Context, id pgtype.UUID) (bool, error)
	// ===================
	// Admin: Client Management
	// ===================
	ListClients(ctx context.Context) ([]Client, error)
	ListSSFEventDeliveries(ctx context.Context, arg ListSSFEventDeliveriesParams) ([]ListSSFEventDeliveriesRow, error)
	ListSSFEventDeliveriesByEvent(ctx context.Context, eventID pgtype.UUID) ([]ListSSFEventDeliveriesByEventRow, error)
	ListSSFEventDeliveriesByStream(ctx context.Context, arg ListSSFEventDeliveriesByStreamParams) ([]ListSSFEventDeliveriesByStreamRow, error)
	ListSSFEventDeliveriesFiltered(ctx context.Context, arg ListSSFEventDeliveriesFilteredParams) ([]ListSSFEventDeliveriesFilteredRow, error)
	ListSSFEvents(ctx context.Context, arg ListSSFEventsParams) ([]SsfEvent, error)
	ListSSFStreamSubjects(ctx context.Context, streamID pgtype.UUID) ([]SsfStreamSubject, error)
	ListSSFStreams(ctx context.Context) ([]SsfStream, error)
	ListSSFStreamsByStatus(ctx context.Context, status string) ([]SsfStream, error)
	ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]IdpSession, error)
	// ===================
	// Admin: User Management
	// ===================
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByStatus(ctx context.Context, arg ListUsersByStatusParams) ([]User, error)
	// Lock a single delivery for immediate processing (used by goroutine)
	// Uses FOR UPDATE SKIP LOCKED to avoid conflicts with DB poller
	// Returns no rows if already locked or not in queued status
	LockSSFEventDeliveryForProcessing(ctx context.Context, id pgtype.UUID) (LockSSFEventDeliveryForProcessingRow, error)
	MarkSSFDeliveryFailed(ctx context.Context, arg MarkSSFDeliveryFailedParams) error
	MarkSSFDeliverySent(ctx context.Context, id pgtype.UUID) error
	RevokeSession(ctx context.Context, id pgtype.UUID) error
	// Revoke all active sessions for a user (used by SLO)
	RevokeUserSessions(ctx context.Context, userID pgtype.UUID) error
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) error
	UpdateClientSecret(ctx context.Context, arg UpdateClientSecretParams) error
	UpdateSSFStream(ctx context.Context, arg UpdateSSFStreamParams) error
	UpdateSSFStreamStatus(ctx context.Context, arg UpdateSSFStreamStatusParams) error
	UpdateUserAccountStatus(ctx context.Context, arg UpdateUserAccountStatusParams) error
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
	UpdateUserEmailVerified(ctx context.Context, arg UpdateUserEmailVerifiedParams) error
	UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
}

var _ Querier = (*Queries)(nil)
