// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID           string             `json:"id"`
	UserSub      string             `json:"user_sub"`
	AccessToken  string             `json:"access_token"`
	IDToken      string             `json:"id_token"`
	RefreshToken *string            `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SsfConfig struct {
	ID        int32              `json:"id"`
	StreamID  *string            `json:"stream_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	Sub       string             `json:"sub"`
	Email     *string            `json:"email"`
	Name      *string            `json:"name"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
