// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountSessionsByUser(ctx context.Context, userSub string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateOrUpdateUser(ctx context.Context, arg CreateOrUpdateUserParams) (User, error)
	// ===================
	// Sessions
	// ===================
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteSSFConfig(ctx context.Context) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionsByUserSub(ctx context.Context, userSub string) (int64, error)
	DeleteUser(ctx context.Context, sub string) error
	// ===================
	// SSF Config
	// ===================
	GetSSFConfig(ctx context.Context) (SsfConfig, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSessionWithUser(ctx context.Context, id string) (GetSessionWithUserRow, error)
	// ===================
	// Users
	// ===================
	GetUser(ctx context.Context, sub string) (User, error)
	ListAllSessions(ctx context.Context) ([]ListAllSessionsRow, error)
	ListSessionsByUser(ctx context.Context, userSub string) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpsertSSFConfig(ctx context.Context, streamID *string) (SsfConfig, error)
}

var _ Querier = (*Queries)(nil)
